# Generated by Django 5.2.16 on 2026-07-16 11:48

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[apps.common.validators.validate_phone],
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("service", models.CharField(max_length=100)),
                (
                    "meeting_date",
                    models.DateField(
                        validators=[apps.common.validators.validate_future_date]
                    ),
                ),
                ("meeting_time", models.TimeField()),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-meeting_date", "-meeting_time"],
                "unique_together": {("meeting_date", "meeting_time")},
            },
        ),
    ]
