# Generated by Django 5.2.16 on 2026-07-16 17:40

import apps.common.validators.common_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meetingbooking_reference_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingbooking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="meetingbooking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="meetingbooking",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="meetingbooking",
            name="meeting_date",
            field=models.DateField(
                db_index=True,
                validators=[
                    apps.common.validators.common_validator.validate_future_date
                ],
            ),
        ),
        migrations.AlterField(
            model_name="meetingbooking",
            name="meeting_time",
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="meetingbooking",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=20,
                validators=[apps.common.validators.common_validator.validate_phone],
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingbooking",
            constraint=models.UniqueConstraint(
                fields=("meeting_date", "meeting_time"), name="unique_meeting_booking"
            ),
        ),
    ]
