# Generated by Django 5.2.16 on 2026-07-16 19:03

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="address",
            field=apps.common.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="emergency_contact",
            field=apps.common.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone",
            field=apps.common.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
