# Generated by Django 5.2.16 on 2026-07-16 11:48

import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[apps.common.validators.validate_phone],
                    ),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes/",
                        validators=[
                            apps.common.validators.FileValidator(
                                allowed_extensions=["pdf", "doc", "docx"],
                                max_size=5242880,
                            )
                        ],
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="careers.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
    ]
