# Generated by Django 5.2.16 on 2026-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_create_test_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
