# Generated by Django 5.2.16 on 2026-07-16 17:40

import apps.common.validators.common_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0003_jobapplication_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=20,
                validators=[apps.common.validators.common_validator.validate_phone],
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("job", "email"), name="unique_job_application"
            ),
        ),
    ]
