# Generated by Django 5.2.16 on 2026-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
