# Generated by Django 5.2.16 on 2026-07-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_newslettersubscription_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscription",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="subscribed_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
