# Generated by Django 5.2.16 on 2026-07-16 17:40

import apps.common.validators.common_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=20,
                validators=[apps.common.validators.common_validator.validate_phone],
            ),
        ),
    ]
